export const DEFAULT_STATE = {
  peter: {
    name: 'Peter',
    age: 38,
    retirementAge: 55,
    salary: 226139,
    bonusType: 'percent',
    bonusPercent: 15,
    bonusFixed: 0,
    rsuAnnual: 50000,
    otherIncome: 0,
    k401Balance: 350000,
    iraBalance: 50000,
    rothBalance: 80000,
    brokerageBalance: 327000,
    hsaBalance: 20000,
    employerMatchRate: 4,
    k401Contribution: 23000,
    iraContribution: 7000,
    rothContribution: 0,
    brokerageContribution: 30000,
    hsaContribution: 0,
    studentLoanBalance: 0,
    studentLoanRate: 0,
    carLoanBalance: 0,
    carLoanRate: 0,
    otherDebtBalance: 0,
    otherDebtRate: 0,
    healthcareSelfPay: 800,
    healthcareEmployer: true,
  },
  jennifer: {
    name: 'Jennifer',
    age: 36,
    retirementAge: 53,
    salary: 226139,
    bonusType: 'percent',
    bonusPercent: 15,
    bonusFixed: 0,
    rsuAnnual: 0,
    otherIncome: 0,
    k401Balance: 150000,
    iraBalance: 0,
    rothBalance: 0,
    brokerageBalance: 0,
    hsaBalance: 0,
    employerMatchRate: 4,
    k401Contribution: 23000,
    iraContribution: 0,
    rothContribution: 7000,
    brokerageContribution: 0,
    hsaContribution: 0,
    studentLoanBalance: 0,
    studentLoanRate: 0,
    carLoanBalance: 0,
    carLoanRate: 0,
    otherDebtBalance: 0,
    otherDebtRate: 0,
    healthcareSelfPay: 800,
    healthcareEmployer: true,
  },
  realEstate: {
    homeValue: 1413600,
    mortgageBalance: 953575,
    monthlyMortgage: 5800,
    mortgageRate: 3.25,
    mortgageYearsRemaining: 25,
    otherRealEstateValue: 0,
  },
  shared: {
    cashSavings: 15316,
    savingsRateType: 'dollar',
    savingsRatePercent: 20,
    savingsRateDollar: 5000,
    currentAnnualSpending: 120000,
    retirementAnnualSpending: 100000,
    essentialExpenses: 60000,
    discretionaryExpenses: 40000,
    expectedReturn: 7,
    inflationRate: 3,
    peterSocialSecurity: 2800,
    jenniferSocialSecurity: 2200,
    peterSSAge: 67,
    jenniferSSAge: 67,
    homeAppreciationRate: 3.5,
    includeHomeEquity: true,
    ssSafeEstimate: false,
    leanFireAmount: 40000,
    fatFireAmount: 150000,
    baristaPartTimeIncome: 24000,
  },
  checklist: {
    healthcareBridge: { status: 'not-started', notes: '' },
    accountAccess: { status: 'not-started', notes: '' },
    socialSecurity: { status: 'not-started', notes: '' },
    taxStrategy: { status: 'not-started', notes: '' },
    collegeFunding: { status: 'not-started', notes: '' },
    estatePlanning: { status: 'not-started', notes: '' },
    rothLadder: { status: 'not-started', notes: '' },
    emergencyFund: { status: 'in-progress', notes: 'Currently at $15,316 — targeting 6 months of expenses' },
  },
  snapshots: [],
  lastUpdated: null,
}
